import type { Client } from './schema';

// This is a mock database. In a real application, you would use a database.
// The data will reset every time the server restarts.
export let clients: Omit<Client, 'placaVehiculo'>[] = [
  {
    id: '1',
    codTipoId: 'C',
    codIdSujeto: '123456789',
    nomSujeto: 'Juan Perez',
    direccion: 'Calle Falsa 123',
    ciudad: 'Springfield',
    telefono: '555-1234',
    numOperacion: 'OP-001',
    fecConcesion: new Date('2023-01-15'),
    valOperacion: 5000,
    valorPago: 5000,
    fecVencimiento: new Date('2024-01-15'),
    valorVencido: 0,
    usuario: 'api_user',
    estado: 'al dia',
  },
  {
    id: '2',
    codTipoId: 'R',
    codIdSujeto: '987654321',
    nomSujeto: 'Maria Garcia',
    direccion: 'Avenida Siempreviva 742',
    ciudad: 'Shelbyville',
    telefono: '555-5678',
    numOperacion: 'OP-002',
    fecConcesion: new Date('2022-11-20'),
    valOperacion: 10000,
    valorPago: 8000,
    fecVencimiento: new Date('2023-11-20'),
    valorVencido: 2000,
    usuario: 'api_user',
    estado: 'adeuda',
  },
  {
    id: '3',
    codTipoId: 'C',
    codIdSujeto: '112233445',
    nomSujeto: 'Carlos Lopez',
    direccion: 'Boulevard 456',
    ciudad: 'Capital City',
    telefono: '555-8765',
    numOperacion: 'OP-003',
    fecConcesion: new Date('2021-05-10'),
    valOperacion: 7500,
    valorPago: 7500,
    fecVencimiento: new Date('2022-05-10'),
    valorVencido: 0,
    usuario: 'api_user',
    estado: 'retirado',
  },
];